// AUTO-GENERATED by scripts/optimize-avatars.mjs | do not edit by hand.
// Preset avatar album. Files live in public/avatars/ (96px WebP).

export interface AvatarPreset {
  id: string;
  label: string;
  src: string;
}

export const AVATAR_PRESETS: AvatarPreset[] = [
  {
    "id": "bear",
    "label": "Bear",
    "src": "/avatars/bear.webp"
  },
  {
    "id": "boy",
    "label": "Boy",
    "src": "/avatars/boy.webp"
  },
  {
    "id": "businessman",
    "label": "Businessman",
    "src": "/avatars/businessman.webp"
  },
  {
    "id": "cat",
    "label": "Cat",
    "src": "/avatars/cat.webp"
  },
  {
    "id": "chicken",
    "label": "Chicken",
    "src": "/avatars/chicken.webp"
  },
  {
    "id": "dog",
    "label": "Dog",
    "src": "/avatars/dog.webp"
  },
  {
    "id": "giraffe",
    "label": "Giraffe",
    "src": "/avatars/giraffe.webp"
  },
  {
    "id": "human",
    "label": "Human",
    "src": "/avatars/human.webp"
  },
  {
    "id": "lion",
    "label": "Lion",
    "src": "/avatars/lion.webp"
  },
  {
    "id": "male",
    "label": "Male",
    "src": "/avatars/male.webp"
  },
  {
    "id": "man-1",
    "label": "Man 1",
    "src": "/avatars/man-1.webp"
  },
  {
    "id": "man-2",
    "label": "Man 2",
    "src": "/avatars/man-2.webp"
  },
  {
    "id": "man-3",
    "label": "Man 3",
    "src": "/avatars/man-3.webp"
  },
  {
    "id": "man-4",
    "label": "Man 4",
    "src": "/avatars/man-4.webp"
  },
  {
    "id": "man",
    "label": "Man",
    "src": "/avatars/man.webp"
  },
  {
    "id": "meerkat",
    "label": "Meerkat",
    "src": "/avatars/meerkat.webp"
  },
  {
    "id": "panda",
    "label": "Panda",
    "src": "/avatars/panda.webp"
  },
  {
    "id": "penguin",
    "label": "Penguin",
    "src": "/avatars/penguin.webp"
  },
  {
    "id": "profile",
    "label": "Profile",
    "src": "/avatars/profile.webp"
  },
  {
    "id": "rabbit",
    "label": "Rabbit",
    "src": "/avatars/rabbit.webp"
  },
  {
    "id": "user-1",
    "label": "User 1",
    "src": "/avatars/user-1.webp"
  },
  {
    "id": "user-2",
    "label": "User 2",
    "src": "/avatars/user-2.webp"
  },
  {
    "id": "user",
    "label": "User",
    "src": "/avatars/user.webp"
  },
  {
    "id": "woman-1",
    "label": "Woman 1",
    "src": "/avatars/woman-1.webp"
  },
  {
    "id": "woman-2",
    "label": "Woman 2",
    "src": "/avatars/woman-2.webp"
  },
  {
    "id": "woman",
    "label": "Woman",
    "src": "/avatars/woman.webp"
  }
];

/** A random preset src | used by the "surprise me" option. */
export function randomAvatar(): AvatarPreset {
  return AVATAR_PRESETS[Math.floor(Math.random() * AVATAR_PRESETS.length)];
}
